[package]
name = "intel_cache_server"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intel_cache_lib = { version="1.0.0", path = "../intel-cache-lib" }
