[package]
name = "intel_cache_server"
version = "1.0.0"
authors = ["case-prudolicce"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intel-cache-lib = { version="1.0.0",path = "../intel-cache-lib" }
